### ISSUE TITLE
The demo crashes in caikit v0.15

### ISSUE THREAD

**Issue by itaijj** [caikit/caikit-huggingface-demo#22]
The hugging face demo is broken now and don't work with caikit v0.15 because of the change with RuntimeGRPCServer API change
`    with RuntimeGRPCServer(
TypeError: __init__() got an unexpected keyword argument 'inference_service'`
can you please fix it?
we

 need some working example with the latest version with REST for the SPARK demo next month

**Comment by markstur** [comment]
Thanks for reporting this.

It should have been clear that the demo app only works with what is specified in requirements.txt, but looking back at the README I am not seeing any specific call-out of the caikit prereq or other library prereqs.  I think I decided that stating that the requirements are prerequisites was redundant and unnecessarily extra wordy.  Does it make sense to say "You must have the required version of caikit (and the other requirements)" before the instruction to install requirements.txt?  Pinned versions are used.  Maybe a few extra words in the README would help others avoid this problem?

Otherwise caikit 0.x upgrades are always assumed to be breaking changes (as opposed to 0.x.y bumps).  I added a new issue for the upgrade work #23.  That's how we generally assign and close the regular maintenance updates vs "crash" bugs.
